spring:
  #*****
  #h2
  #*****
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  #*****
  #jpa
  #*****
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  #*****
  #datasource
  #*****
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver


# Actuators
management:
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers


logging:
  level:
    org:
      springframework:
        web: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  error:
    include-message: always