spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER


# Actuators
management:
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers